version: '2'
services:
  logstash-collector-config:
    restart: always
    image: simpletechs/rancher_logstash-config:v0.2.0-smpl1
    labels:
      io.rancher.container.hostname_override: container_name
      logspout.exclude: 'true'
    environment:
      LOGSPOUT: ignore

  logstash-collector:
    restart: always
    tty: true
    volumes_from:
    - logstash-collector-config
    command:
    - logstash
    - -f
    - /etc/logstash
    image: docker.elastic.co/logstash/logstash:6.2.0
    environment:
      xpack.monitoring.enabled: false
      LOGSPOUT: ignore
    stdin_open: true
    volumes:
    - '/var/log:/host/var/log:ro'
    user: root
    labels:
      io.rancher.sidekicks: logstash-collector-config
      io.rancher.scheduler.global: 'true'
      io.rancher.container.hostname_override: container_name
      logspout.exclude: 'true'

  logspout:
    environment:
      EXCLUDE_LABEL: "io.rancher.container.system"
      LOGSPOUT: ignore
      ROUTE_URIS: logstash://logstash:5000
      INACTIVITY_TIMEOUT: 1m
      ALLOW_TTY: true
    links:
    - logstash-collector:logstash
    labels:
      io.rancher.scheduler.global: "true"
      io.rancher.container.hostname_override: container_name
    tty: true
    image: adopteunops/logspout-logstash:20170823
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
